Issue#60
Allegheny-Ethical-CS/GatorMiner pull request #76
Opened 2021-04-06 13:44 UTC by Nathandloria

In this pull request we created a new landing page to reduce redundancy generated by the README. The new landing page is in markdown format and it displays a lot of helpful information about the tool. It also shows quick instructions further explaining how to use the tools provided by GatorMiner.

## What is the current behavior?

closes #60 

## What is the new behavior if this PR is merged?

New, less redundant landing page.

Please describe the pull request as one of the following:

- [ ] Bug fix
- [ ] Breaking change
- [x] New feature
- [x] Documentation update
- [ ] Other 

### Other information

### This PR has:

- [x] Commit messages that are correctly formatted
- [ ] Tests for newly introduced code
- [x] Docstrings for newly introduced code

#### Developers

@PaigeCD @caldwella2 @angusn8 @connellyw @Nathandloria

2021-04-07 18:35 UTC, enpuyou requested changes
I haven't really gotten the chance to read into the details. Most are great, just one comment below. Another thing, can you create a folder named `docs`, and just put this markdown file in there. It seems like there will be more documentation coming up soon, so I would like to have them all in one place. Thanks!

2021-04-07 18:35 UTC, enpuyou commented on LANDING_PAGE.md
> +<img src="resources/images/similarity.png" alt="browser" style="width:100%"/>
I didn't know about this before! It's a good thing to know. I would just like to maybe have a source that can refer to here.

2021-04-07 21:13 UTC, noorbuchi commented
I think that your PR has multiple issues resulting from this commit 7b745607ca22d3f3d2b33da6afe547bff2673708 . This reverts very important fixes. Please make sure to resolve this by restoring the deleted files and re-adding the important fixes

2021-04-10 05:01 UTC, noorbuchi requested changes
I think the new landing page looks great! I requested few small changes that you should address before merging this PR. Thanks for working on this helpful documentation!

2021-04-14 18:27 UTC, enpuyou approved these changes
Hi @Nathandloria, I think this PR is good! I have just added an `mdl` check into the Travis CI, so it would enforce markdown rules on documents in `docs` folder. Should anything fail (there is probably not, but just in case), just do a quick fix, I don't think it would be anything substantial. Thanks again!

2021-04-14 19:06 UTC, corlettim approved these changes

2021-04-14 19:27 UTC, munzekm approved these changes

2021-04-14 20:39 UTC, noorbuchi approved these changes

2021-04-14 20:45 UTC, merged